### ISSUE TITLE
Unable to get calls and camera

### ISSUE THREAD

**Issue by edualm** [AfonsoFGarcia/hass-bluecon#18]
Hey,

I was able to get the keys successfully (I think), but I only got 4 entities added: the door lock itself, call status and 2x connection status sensors.

The issue is, this only allows me to open the door. It doesn't alert me of incoming calls neither shows a camera with the latest image, which I think should be supported features.

Is this just not implemented? Or did I input the wrong keys?

Thanks a lot for your work in the project!

**Comment by edualm** [comment]
Looking at the logs I get things like this:

```
2024-12-16 14:58:21.010 ERROR (MainThread) [homeassistant.components.camera] Error while setting up bluecon platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/bluecon/camera.py", line 24, in async_setup_entry
    image = await bluecon.getLastPicture(pairing.deviceId)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bluecon/BlueConAPI.py", line 230, in getLastPicture
    latestCallLog : CallLog | None = max(callLogs or None, key = lambda x: x.getCallDate())
                                     ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

**Comment by edualm** [comment]
I _think_ I'm getting somewhere actually. Basically if the account has no history of call history it all falls apart, but if a call is received data is populated and it starts working. I'll keep analyzing and see if I can get somewhere, and hopefully submit an MR if I get things working!

**Comment by swas** [comment]
Hello @edualm!
How did you get the call notification?
What release are you using?

I have call history on the account 
Release of the repo: 0.7.0-alpha.1

Thanks!

**Comment by edualm** [comment]
Hey @swas,

Latest version. All I did was get a call and after restarting the integration it worked.

It seems a bit unstable so I had to make it restart every 30 minutes. Very hacky but seems to work.

**Comment by swas** [comment]
Thanks @edualm! 

I don't have the "Fermax call status" entity
What values are you set for this config options? 

![Screenshot_2025-01-02-11-05-45-048_io homeassistant companion android-edit](https://github.com/user-attachments/assets/c24b53ab-b1b3-4721-bd95-3b1496cffa77)

**Comment by edualm** [comment]
I don't think the project owner wants us to share those values 😄

Let me tell you though that my App ID ends in `6fd4`, Project ID ends in `-blue` and FCM Package ID ends in `.app`. I hope that guides you in the right direction!

**Comment by swas** [comment]
Thanks @edualm

I'm on the right way
The only distmatch is the "Project ID"

It's posible to get that value?
It's not a secret key...

Thanks!
Greetings
